### ISSUE TITLE
App crashed after reloading data to recycler view 

### ISSUE THREAD

**Issue by RanjeethKumar55** [pankaj89/MasterExoPlayer#12]
Hi pankaj,

App is getting crashed after loading data to recycler view ,  Please look into the issue
   

 java.lang.IllegalStateException: recyclerView.getChildAt(0) must not be null
        at com.master.exoplayer.MasterExoPlayerHelper$onScrollListener$1.onScrolled(MasterExoPlayerHelper.kt:191)
Thanks in advance

**Comment by pankaj89** [comment]
Hello Ranjeeth,
Can you try this version

`implementation 'com.github.pankaj89:MasterExoPlayer:-SNAPSHOT'`

If its going to work i will create a new release. Let me know.

**Comment by RanjeethKumar55** [comment]
thank you , it is working now

**Comment by pankaj89** [comment]
Hello Ranjeeth,
You can now use new version

`implementation 'com.github.pankaj89:MasterExoPlayer:1.4.5'`

**Comment by RanjeethKumar55** [comment]
okay thanks alot

**Comment by RanjeethKumar55** [comment]
hi pankaj,

how to add thumbnail image ?

thanks and regards
Ranjeeth Kumar

**Comment by pankaj89** [comment]
Hello Ranjeeth

To add thumbnail image, just place imageview in your item layout and send that reference to MasterExoPlayer.image inside onBindView of adapter. rest library will take care to hide or show it while playing video.

Note: Load thumbnail image on your imageview with any way like glide.
You can take a reference from MainActivity.kt 

Thanks
