### ISSUE TITLE
delay in play

### ISSUE THREAD

**Issue by Naveenkant93** [pankaj89/MasterExoPlayer#16]
Hi first of all thanks for the best solution.
I am facing an issue. I am using HLS videos. But it takes 2-3 second to play the video, Till that time it shows black screen.
Even if a video played before and again if I Switch to old video still it behave like 2-3 sec black screen then video. Is any possibility to use preLoad while HLS.

Thanks

**Comment by pankaj89** [comment]
Hello
Have you tried to set imageView of MasterExoPlayer it will show thumbnail of your choice till video starts actual playing just like Instagram. so with this it will not show 2-3 sec blank screen.

**Comment by Naveenkant93** [comment]
Yes @pankaj89 I used-

I used an ImageView in xml layout and using 1 asset in image. Image appears when item comes to focus and disappears, After that 2-3 sec a blank screen comes and after that video plays
binding.frame.imageView = binding.image

**Comment by Naveenkant93** [comment]
@pankaj89 I checked this and find one thing, This library is using old version of Exoplayer. I updated the version in
com.google.android.exoplayer:exoplayer:2.13.3
With this version I am able to create cache for videos which is too fast and videos are not taking time.

**Comment by Naveenkant93** [comment]
@pankaj89 Thanks Again. I updated exoplayer in lib and it worked like charm.
Thanks.

Closing this issue.

**Comment by pardeepmg** [comment]
@Naveenkant93 Can you please share your MasterExoPlayerHelper code after updating the version ?
