### ISSUE TITLE
This library doesn't work inside nestedscrollview.

### ISSUE THREAD

**Issue by arjunEbiz** [pankaj89/MasterExoPlayer#4]
Inside nestedscrollview, auto play video doesn't work but without nestedscrollview it it working fine. Can you please guide me, how can I get auto play video inside Nestedscrollview.

**Comment by pankaj89** [comment]
Inside Nestedscrollview all items of RecyclerView is automatically expanded, so it will not work inside NestedScrollView. 

**Points to note**: Even pagination is also not working inside NestedScrollView.
**Alternates**: If possible in some situation we can use coordinate layout with RecyclerView, so this library will work there, check if you can use CoordinateLayout to fullfill your requirement. use that.
