### ISSUE TITLE
reziseMode.AspectRatioFrameLayout

### ISSUE THREAD

**Issue by lgvg92** [pankaj89/MasterExoPlayer#5]
Hi! I hope you well!
I have been working with your library and its really helpfull. I just have one question,
I want to set Resize Mode to the player view to be RESIZE_MODE_FIT but after so many tries I can't achieve this. is it possible? and how could I do this? 
thanks in advance

**Comment by pankaj89** [comment]
Thanks for suggestion, will add this feature in next release.

**Comment by lgvg92** [comment]
Thank you so much for your reply. Do you have any estimation about the next release date? Many thanks for your feedback

**Comment by pankaj89** [comment]
Here it is, You can now use
implementation 'com.github.pankaj89:MasterExoPlayer:1.4.4'

Now you can use getPlayerView() immediately after instance creation of MasterExoPlayerHelper

In kotlin
```
masterExoPlayerHelper.getPlayerView().apply {
      resizeMode = AspectRatioFrameLayout.RESIZE_MODE_ZOOM
}
```

In Java
```
masterExoPlayerHelper.getPlayerView().setResizeMode(
```

**Comment by lgvg92** [comment]
I just try this and it works perfectly! thanks a lot! :D
