### ISSUE TITLE
First video doesn't play.

### ISSUE THREAD

**Issue by uzaysan** [pankaj89/MasterExoPlayer#6]
I'm using your library. And latest version has a lot of improvments. But first video doesnt play. 
I attached a listener to player. 

```
 @Override
 public void onError(@org.jetbrains.annotations.Nullable ExoPlaybackException e) {
       holder.videoProgress.setVisibility(View.GONE);
       holder.muteControlLayout.setVisibility(View.INVISIBLE);
 }
```

Listener triggers on error method when I scroll recycler view to top. I mean really top. On error method only triggers when there is no more space to scroll.  and of course first video doesnt play no matter what. 

I tried to investigate error but seems like Listener throws null error.

When I check
```
i(e==null){
    //its true
}
```

Do you have any Idea why this happens?

**Comment by uzaysan** [comment]
I kept trying and seems like top video plays If I scroll down a little. But when no more space to scroll to top player stops. I recorded my phone screen so you can see what happens. Here is the video:
https://streamable.com/28x5v6

**Comment by seungjunGong** [comment]
> I kept trying and seems like top video plays If I scroll down a little. But when no more space to scroll to top, player stops. I recorded my phone screen so you can see what happens. Here is the video: https://streamable.com/28x5v6

Have you ever solved this problem? I also have the same symptoms.
