### ISSUE TITLE
Can this library be used for Autoplaying Youtube videos in Recyclerview?

### ISSUE THREAD

**Issue by goforbg** [pankaj89/MasterExoPlayer#7]
Trying to implement something similar to tiktok, queueing Youtube videos. Can it be done using this library?

**Comment by pankaj89** [comment]
No, As YouTube don't provide any public link which can be played on any player.

**Comment by goforbg** [comment]
People do stream YouTube videos on Exo using this library that feeds a URL to exo player: https://github.com/HaarigerHarald/android-youtubeExtractor

Just wanted to know if it worked in a recyclerview, will check out and update.

Thanks for the reply.

**Comment by pankaj89** [comment]
Good to know, then you can use that link to play in this player also. with that library integrate use that
downloadUrl.
